<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- PLUGINS -->
    <gazebo>
        <plugin name="${robot_name}_joint_state" filename="libgazebo_ros_joint_state_publisher.so">
            <ros>
                <namespace>/${robot_name}</namespace>
                <!-- <remapping>~/out:=joint_states</remapping> -->
            </ros>
            <update_rate>30</update_rate>

            <joint_name>left_drive_wheel_joint</joint_name>
            <joint_name>right_drive_wheel_joint</joint_name>

            <joint_name>left_castor_wheel_yaw_joint</joint_name>
            <joint_name>right_castor_wheel_yaw_joint</joint_name>
            <joint_name>left_castor_wheel_pitch_joint</joint_name>
            <joint_name>right_castor_wheel_pitch_joint</joint_name>

        </plugin>
    </gazebo>


    <!-- Differential drive -->
    <gazebo>
        <plugin filename="libgazebo_ros_diff_drive.so" name="${robot_name}_differential_drive_controller">
        <ros>
            <namespace>/${robot_name}</namespace>
            <!--
                <argument> -ros-args -remap /cmd_vel:=/${robot_name}/cmd_vel /odom:=/${robot_name}/odom</argument>
            -->
        </ros>

        <!-- wheels -->
        <!-- wheels RMF COMPAT -->
        <left_joint>left_drive_wheel_joint</left_joint>
        <right_joint>right_drive_wheel_joint</right_joint>
        
        <!-- kinematics -->
        <wheel_separation>${wheel_yoff * 2}</wheel_separation>
        <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

        <!-- limits -->
        <max_wheel_torque>10000</max_wheel_torque>
        <max_wheel_acceleration>1000</max_wheel_acceleration>

        <!-- output -->
        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
        <!-- <publish_wheel_tf>false</publish_wheel_tf> -->

        <odometry_frame>${robot_name}/odom</odometry_frame>
        <robot_base_frame>${robot_name}/dummy_link</robot_base_frame>

        </plugin>
    </gazebo>

</robot>